services:
  - type: web
    name: yomo-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: SUPABASE_URL
        value: your-supabase-url
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: your-service-role-key
      - key: CHUTES_URL
        value: your-chutes-url
      - key: CHUTES_API_KEY
        value: your-chutes-api-key
